### ISSUE TITLE
how to prepare feature files and mean/std file

### ISSUE THREAD

**Issue by taalua** [nervjack2/MelHuBERT#2]
Hi,

How to prepare using my own data, e.g., scp, ark, and mean/std files?
Thank you for the work.

**Comment by nervjack2** [comment]
Hello,

You will need to prepare a .csv file that records the data path, label path, and data length. 
Both data and labels are stored in .npy format (https://github.com/nervjack2/MelHuBERT/blob/main/dataset.py#L82).

For the labels, you can use fairseq to perform k-means clustering on your data.(https://github.com/facebookresearch/fairseq/tree/main/examples/hubert/simple_kmeans)

You can either use kaldi or torchaudio to extract log Mel feature, 
an example is at https://github.com/nervjack2/MelHuBERT/blob/main/extract_feature.py#L20

**Comment by taalua** [comment]
Hi, 
Thank you for the info.
How do you compute the mean and std file, is it cepstral mean and variance normalization?, can I use compute-cmvn-stats in Kaldi ?

Thanks.

**Comment by nervjack2** [comment]
No, we compute mean and variance over the whole LibriSpeech 360-hour subset. 
An example is here: [https://github.com/nervjack2/MelHuBERT/blob/main/preprocess/cal_data_mean_var.py](https://github.com/nervjack2/MelHuBERT/blob/main/preprocess/cal_data_mean_var.py)
You should create your own .tsv file by the way.

**Comment by nervjack2** [comment]
I would close the issue first. You can reopen it if you still have any question, thanks!
