### ISSUE TITLE
How to fintune model on ASR task from stage-2?

### ISSUE THREAD

**Issue by zw76859420** [nervjack2/MelHuBERT#6]
Dear authors,

Can you tell me how to finetune a model trained in stage-2 for ASR task?
We can also draw a conclusion of your paper, for ASR Task, we can directly pretrain stage-2 from scratch without training stage-1?

Looking forward to your reply.
Shylock

**Comment by nervjack2** [comment]
Hi Shylock, 

For ASR task finetuning, I suggest implementing it using s3prl or espnet. 
In our paper, we concluded that initializing stage-2 pre-training with stage-1 weights is not beneficial. 
However, training a stage-1 model is still necessary, as the pre-training target for the stage-2 model is constructed by applying k-means clustering to the features from the stage-1 model.

**Comment by zw76859420** [comment]
Thanks for your reply. I understand what you mean.
