### ISSUE TITLE
Missing Mean and Standard Deviation for LibriSpeech 960h in MelHuBERT Checkpoints

### ISSUE THREAD

**Issue by MorenoLaQuatra** [nervjack2/MelHuBERT#7]
Hi,

First, thank you very much for your work on MelHuBERT and for making your checkpoints publicly available. I have been trying to use MelHuBERT models, and I noticed that the mean and standard deviation values are available for the LibriSpeech 100h and 360h datasets but are missing for the 960h version. What can we use for [MelHuBERT-10ms 960-hour stage 2](https://drive.google.com/file/d/18u2u-528uDh5T7R1bp1wvWJ2ygcrNlzx/view?usp=sharing) and [MelHuBERT-20ms 960-hour stage 2](https://drive.google.com/file/d/1Fn_C5VoH5iV3LdvBEjvfAsbMPhWFFPdd/view?usp=sharing)?

Specifically, I am referring to the mean and standard deviation values used for normalizing the fbank features, as in the example code for extracting features for MelHuBERT. Without these values, it becomes challenging to correctly use the 960h checkpoint in the same way as the other versions.

Also, can you please suggest which can be the best model to extract features from? Would it be 360h stage 2 as in the paper?

**Comment by nervjack2** [comment]
Hi, 

I have added the mean and standard deviation of 960h.
I would say 960h 20ms stage-2 model is the best model to extract feature.
